[package]
name = "lpfx"
version = "0.1.0"
authors = ["Steven L <steven.leibrock@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portmidi = "*"
clap = "*"
